services:
  postgres:
    image: postgres:16-alpine
    container_name: bdi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_devops_interview
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    depends_on:
      - postgres
    environment:
      DJANGO_SECRET_KEY: "changeme"
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"
      DB_NAME: backend_devops_interview
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: "5432"
    ports:
      - "8000:8000"
    volumes:
      - .:/app:delegated
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge