apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-devops-interview.fullname" . }}
  labels:
    {{- include "backend-devops-interview.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend-devops-interview.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend-devops-interview.fullname" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "backend-devops-interview.fullname" . }}-config
            - secretRef:
                name: {{ include "backend-devops-interview.fullname" . }}-secrets
          readinessProbe:
            httpGet:
              path: /api/posts
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/posts
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
