apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-devops-interview.fullname" . }}-secrets
  labels:
    {{- include "backend-devops-interview.labels" . | nindent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
